### ISSUE TITLE
Broken deployment in MacOS using Hatch

### ISSUE THREAD

**Issue by alvarocurt** [Telefonica/one-deploy#4]
**Description**
Hatch breaks in any plabook that tries to perform tasks in localhost, due to how Hatch handles paths

**To Reproduce**
The error happened while running ceph.yml, at task 
```yaml
    - name: Generate monitor initial keyring
      ceph_key:
        state: generate_secret
      register: monitor_keyring
      delegate_to: localhost
      become: false
      run_once: true
      no_log: "{{ no_log_on_ceph_key_tasks }}"
      when:
        - initial_mon_key is skipped
          or
          initial_mon_key is not succeeded
```
during role `ceph-mon`. This is the error:
```bash
TASK [ceph-mon : Generate monitor initial keyring] ************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/hixxXXX/Developer/_PROYECTOS/_REPOS/one-deploy/vendor/ceph-ansible/roles/ceph-mon/tasks/deploy_monitors.yml:23
jueves 24 abril 2025  19:11:33 +0200 (0:00:00.017)       0:05:39.102 ********** 
fatal: [oneedge5gs-01 -> localhost]: FAILED! => changed=false 
  module_stderr: |-
    /bin/sh: /Users/hixxXXX/Library/Application: No such file or directory
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 127
```

The error can also be reproduced by entering the hatch environment itself
```bash
#hatch env run -e ceph -- bash
#which python
/Users/hixxXXX/Library/Application Support/hatch/env/virtual/one-deploy/r2fGSZkR/ceph/bin/python
#sudo ansible localhost -m setup
Password:
localhost | FAILED! => {
    "changed": false,
    "module_stderr": "/bin/sh: /Users/hixxXXX/Library/Application: No such file or directory\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 127
}
```
It is clear that ansible can't handle python paths with spaces, and therefore any task run locally will fail

# Conclusion
I guess I could move development to a VM or a container, but this again proves hatch useless for development in MacOS...
I'll try to create a devcontainer for this proyect and install the ansible binaries directly there.
